import Head from 'next/head'
import { Header, Banner, Map } from '../components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Math puzzle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <Map />

    </div>
  )
}
